### ISSUE TITLE
[FEAT] Sample Config Request of CIDR Filter

### ISSUE THREAD

**Issue by honwen** [compassd/dcompass#51]
base config like: https://github.com/LEXUGE/dcompass/blob/main/configs/example.yaml

and filter a(some) cidr, such as `203.208.32.0/19`, more [info](http://ip.bczs.net/203.208.32.0)

**Comment by LEXUGE** [comment]
Hi, sorry for the delay.
I am not sure if it is necessary to manually sort out the Google China IP range, as the GeoIP database should already take care of it.

However, I think it is a good idea though to add more versatile samples. I am considering maintaining a config base, if you are interested, please don't hesitate to reply back.

**Comment by honwen** [comment]
> Hi, sorry for the delay.
> I am not sure if it is necessary to manually sort out the Google China IP range, as the GeoIP database should already take care of it.
> 
> However, I think it is a good idea though to add more versatile samples. I am considering maintaining a config base, if you are interested, please don't hesitate to reply back.

sure, and I also maintain a [makefile for openwrt](https://github.com/honwen/openwrt-dnsmasq-extra/tree/master/dcompass),  `more versatile samples` will help a lot
