### ISSUE TITLE
[FEAT] 望Release增加mipsel和mips架构可执行文件

### ISSUE THREAD

**Issue by fox85** [compassd/dcompass#64]
感谢作者~~~希望作者考虑一下增加编译mipsel和mips架构可执行文件，使其能够在小型嵌入式路由器OpenWrt系统使用上如此好的软件

**Comment by LEXUGE** [comment]
目前的问题是ring 没有支持 mips，因此没法直接交叉编译
我们可以考虑使用nativetls，或许可以解决这个问题

**Comment by LEXUGE** [comment]
但是编译出来的binary可能就不portable了，和openssl强相关

**Comment by LEXUGE** [comment]
https://github.com/compassd/dcompass/releases/tag/build-20210912_1158
经过不断的努力，现在我们已经能够 build mipsel 和 mips 框架的 binary 了
TLS backend 采用的是静态链接的 Openssl, 所以还是 portable 的。
欢迎测试 + 反馈

**Comment by fox85** [comment]
感谢作者大佬！！！

**Comment by LEXUGE** [comment]
Closing now as no further problems were reported. Feel free to reopen or file a new issue if needed.
