### ISSUE TITLE
[FEAT] 是否考虑支持EDNS呢？

### ISSUE THREAD

**Issue by xsy2004** [compassd/dcompass#71]
支持EDNS使得用户得到对应IP地区的CDN调度地址

**Comment by LEXUGE** [comment]
考虑支持EDNS，不过这需要拿到用户的公网IP，目前还需要研究来进一步实现

**Comment by xsy2004** [comment]
> 考虑支持EDNS，不过这需要拿到用户的公网IP，目前还需要研究来进一步实现

可以参考overture的代码，那个是完美支持的
