### ISSUE TITLE
请问新版本配置文件应如何填写过滤特定qtype INT整数值类型？

### ISSUE THREAD

**Issue by fox85** [compassd/dcompass#75]
又来向大佬提问了，:D
请问新版本配置文件应如何填写过滤特定qtype INT整数值类型？
写了N个写法都不行

如：
---
verbosity: "info"
cache_size: 1
address: 127.0.0.1:5359
table:
  start:
    if: |
      qtype([AAAA, SOA, INT65]) && (true)
    then:
      # A list of actions is allowed here
      - blackhole
      # The next tag to go
      - end
    else:
      - query: smartdns
      - end

upstreams:
  smartdns:
    udp:
      addr: 192.168.181.1:5359

执行后提示：
Using the config file specified: test.txt
Error: unknown variant `INT65`, expected one of `A`, `NS`, `MD`, `MF`, `CNAME`, `SOA`, `MB`, `MG`, `MR`, `NULL`, `WKS`, `PTR`, `HINFO`, `MINFO`, `MX`, `TXT`, `RP`, `AFSDB`, `X25`, `ISDN`, `RT`, `NSAP`, `NSAPPTR`, `SIG`, `KEY`, `PX`, `GPOS`, `AAAA`, `LOC`, `NXT`, `EID`, `NIMLOC`, `SRV`, `ATMA`, `NAPTR`, `KX`, `CERT`, `A6`, `DNAME`, `SINK`, `OPT`, `APL`, `DS`, `SSHFP`, `IPSECKEY`, `RRSIG`, `NSEC`, `DNSKEY`, `DHCID`, `NSEC3`, `NSEC3PARAM`, `TLSA`, `SMIMEA`, `HIP`, `NINFO`, `RKEY`, `TALINK`, `CDS`, `CDNSKEY`, `OPENPGPKEY`, `CSYNC`, `ZONEMD`, `SPF`, `UINFO`, `UID`, `GID`, `UNSPEC`, `NID`, `L32`, `L64`, `LP`, `EUI48`, `EUI64`, `TKEY`, `TSIG`, `IXFR`, `AXFR`, `MAILB`, `MAILA`, `ANY`, `URI`, `CAA`, `AVC`, `DOA`, `TA`, `DLV`, `INT`

**Comment by LEXUGE** [comment]
试试看 `INT(65)`?

**Comment by fox85** [comment]
感谢，这样写可以了 🍡
