### ISSUE TITLE
[FEAT] Please provide build script sample for "full cn" feature using 'cargo'

### ISSUE THREAD

**Issue by ljsnogard** [compassd/dcompass#76]
**Is your feature request related to a problem? Please describe.**
Under FreeBSD I want to build `dcompass` with command `cargo build --release --feature "full"`.
And then I got:
```
error: none of the selected packages contains these features: full
```

**Describe the solution you'd like**
A simple enough script to build 'dcompass' with selected feature(s)

**Describe alternatives you've considered**
A pre-built FreeBSD release in the release page shall be good.

**Additional context**
N/A

**Comment by LEXUGE** [comment]
The fact is there is no such feature as “full”. The available ones are `geoip-cn` and `geoip-maxmind`.

**Comment by ljsnogard** [comment]
> The fact is there is no such feature as “full”. The available ones are `geoip-cn` and `geoip-maxmind`.

Thank you for the help. Building with 
```
cargo build --release --features "geoip-cn"
```
succeeded and it works so far so good.
Performance improvement is obvious comparing with a golang-written DNS.

**Comment by LEXUGE** [comment]
Thanks for your support. I am happy to hear more feedbacks in the future.
