### ISSUE TITLE
[BUG] alpine上无法运行

### ISSUE THREAD

**Issue by echowings** [compassd/dcompass#90]
**Describe the bug 发生了什么**
alpine linux上无法运行
apk add build-base
(1/9) Installing libmagic (5.41-r0)
(2/9) Installing file (5.41-r0)
(3/9) Installing musl-dev (1.2.3-r0)
(4/9) Installing libc-dev (0.7.2-r3)
(5/9) Installing g++ (11.2.1_git20220219-r2)
(6/9) Installing make (4.3-r0)
(7/9) Installing fortify-headers (1.1-r1)
(8/9) Installing patch (2.7.6-r7)
(9/9) Installing build-base (0.5-r3)
curl -fsSL https://github.com/compassd/dcompass/releases/download/build-20220707_1120/dcompass-x86_64-unknown-linux-gnu-full -o dcompass && \
    chmod +x dcompass 

c5d07d22d6b1:/usr/bin# ls -alh ./dcompass
-rwxr-xr-x    1 root     root       10.5M Sep  3 10:24 ./dcompass

c5d07d22d6b1:/usr/bin# ./dcompass
/bin/sh: ./dcompass: not found

**To Reproduce 如何重现**
1. Go to '...

**Screenshots 截图**

**Version & Platform (please complete the following information) 版本信息**
 - Variant: [e.g. `aarch64-unknown-linux-musl-cn`]
- OS: [e.g. Windows 10 / macOS / Linux]
 - Version [e.g. build-20210109_1254]

**Additional context 附加信息**

**Comment by LEXUGE** [comment]
尝试一下musl版本？glibc在不同发行版上会有版本不兼容

**Comment by echowings** [comment]
musl是好的

**Comment by LEXUGE** [comment]
你可以尝试安装兼容 Ubuntu 18 的 glibc 版本，或者使用 musl 版本。

如果还有相关问题欢迎 reopen
