### ISSUE TITLE
[BUG] Domain matcher 会 match 父级域名？

### ISSUE THREAD

**Issue by tywtyw2002** [compassd/dcompass#97]
如果Domain.txt 内容如下

```
tejia.taobao.com
temai.m.taobao.com
tui.taobao.com
```

`taobao.com` 和 `m.taobao.com` 会被错误的match上。

看了下代码，看起来逻辑上没有判读，域名label中间的lvs 是过路节点还是需要match的节点。
```
    pub fn matches(&self, domain: &Dname<Bytes>) -> bool {
        let mut ptr = &self.root;
        for lv in domain.iter().rev() {
            if ptr.next_lvs.is_empty() {
                break;
            }
            // If not empty...
            ptr = match ptr.next_lvs.get(&lv.to_owned()) {
                Some(v) => v,
                None => return false,
            };
        }
        true
    }
```

**Comment by tywtyw2002** [comment]
还是有问题，这回应该match的域名不match了。

这句话看起来不会被执行。
比如说 `tejia.taobao.com`，最后一次loop把ptr 指向 `tejia`，然后loop 就结束了。

```
            if ptr.next_lvs.is_empty() {
                return true;
            }
```

看样子好像只能在levelnode里面加个bool了。

**Comment by LEXUGE** [comment]
> 还是有问题，这回应该match的域名不match了。
> 
> 这句话看起来不会被执行。 比如说 `tejia.taobao.com`，最后一次loop把ptr 指向 `tejia`，然后loop 就结束了。
> 
> ```
>             if ptr.next_lvs.is_empty() {
>                 return true;
>             }
> ```
> 
> 看样子好像只能在levelnode里面加个bool了。

test case 里包括了 `tejia.taobao.com` ，能提供更具体可复现的问题吗

**Comment by LEXUGE** [comment]
最新的 build 已经修复了，test case 里也有 cover。
